//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dxwndhost.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MFXTEXTYPE                  129
#define IDD_TARGET                      130
#define IDR_ACTIVE                      131
#define IDR_MENU_POPUP                  132
#define IDR_MENU_SYSTRAY                133
#define IDI_DXWAIT                      137
#define IDI_DXIDLE                      138
#define IDI_DXRUN                       140
#define IDI_ICON2                       141
#define IDI_RUN0                        142
#define IDI_RUN1                        143
#define IDI_RUN2                        144
#define IDI_RUN3                        145
#define IDI_RUN4                        146
#define IDI_RUN5                        147
#define IDI_RUN6                        148
#define IDD_STATUS                      149
#define IDD_TIMESLIDER                  150
#define IDD_TAB_PROGRAM                 152
#define IDD_TAB_LOG                     153
#define IDB_BIGICONS                    153
#define IDD_TAB_DIRECTX                 154
#define IDD_TAB_MOUSE                   155
#define IDB_BITMAP1                     155
#define IDB_SMALLICONS                  155
#define IDD_TAB_TIMING                  156
#define IDD_TAB_WINDOW                  157
#define IDD_TAB_EMPTY                   158
#define IDD_TAB_OPENGL                  159
#define IDD_TAB_COMPAT                  160
#define IDD_TAB_GDI                     161
#define IDD_TAB_COLOR                   162

#define IDC_AUTO                        300
#define IDC_DIRECTX1                    301
#define IDC_DIRECTX7                    302
#define IDC_DIRECTX8                    303
#define IDC_DIRECTX9                    304
#define IDC_NODIRECTX                   305
#define IDC_DIRECTX10                   306
#define IDC_DIRECTX11                   307

#define IDC_FILE                        1000
#define IDC_OPEN                        1001
#define IDC_STATUSINFO                  1005
#define IDC_VERSION                     1006
#define IDC_UNNOTIFY                    1007

#define IDC_NOEMULATESURFACE            1008
#define IDC_EMULATEBUFFER               1009
#define IDC_LOCKEDSURFACE               1010
#define IDC_EMULATESURFACE              1011

#define IDC_MODIFYMOUSE                 1012
#define IDC_OUTTRACE                    1013
#define IDC_HANDLEDC                    1014
#define IDC_SAVELOAD                    1015
#define IDC_INITX                       1016
#define IDC_INITY                       1017
#define IDC_MINX                        1018
#define IDC_MINY                        1019
#define IDC_MAXX                        1020
#define IDC_MAXY                        1021
#define IDC_MAXFPS                      1022
#define IDC_MODULE                      1023
#define IDC_OPENGLLIB                   1024
#define IDC_AUTOREFRESH                 1025
#define IDC_FIXWINFRAME                 1026
#define IDC_HIDEHWCURSOR                1027
#define IDC_ENABLECLIPPING              1028
#define IDC_SHOWHWCURSOR                1029
#define IDC_VIDEOTOSYSTEMMEM            1030
#define IDC_FIXTEXTOUT                  1031
#define IDC_KEEPCURSORWITHIN            1032
#define IDC_USERGB565                   1033
#define IDC_SUPPRESSDXERRORS            1034
#define IDC_PREVENTMAXIMIZE             1035
#define IDC_OUTWINMESSAGES              1036
#define IDC_OUTDXTRACE                  1037
#define IDC_DXPROXED                    1038
#define IDC_TITLE                       1039
#define IDC_SLOW                        1040
#define IDC_CLIPCURSOR                  1041
#define IDC_INITTS                      1042
#define IDC_CLIENTREMAPPING             1043
#define IDC_HANDLEALTF4                 1044
#define IDC_LOCKWINPOS                  1045
#define IDC_POSX                        1046
#define IDC_POSY                        1047
#define IDC_SIZX                        1048
#define IDC_SIZY                        1049
#define IDC_HOOKCHILDWIN                1050
#define IDC_MESSAGEPROC                 1051
#define IDC_MAPGDITOPRIMARY             1052
#define IDC_RECOVERSCREENMODE           1053
#define IDC_REFRESHONRESIZE             1054
#define IDC_BACKBUFATTACH               1055
#define IDC_ASSERT                      1056
#define IDC_INIT8BPP                    1057
#define IDC_INIT16BPP                   1058
#define IDC_KEEPCURSORFIXED             1059
#define IDC_LOCKWINSTYLE                1060
#define IDC_FIXPARENTWIN                1061
#define IDC_LOGENABLED                  1062
#define IDC_CURSORTRACE                 1063
#define IDC_IMPORTTABLE                 1064
#define IDC_HANDLEEXCEPTIONS            1065
#define IDC_BLITFROMBACKBUFFER          1066
#define IDC_OUTDEBUG                    1067
#define IDC_SUPPRESSCLIPPING            1068
#define IDC_MODALSTYLE                  1069
#define IDC_KEEPASPECTRATIO             1070
#define IDC_LIMITRESOURCES              1071
#define IDC_SUPPRESSIME                 1072
#define IDC_SETCOMPATIBILITY            1073
#define IDC_FIXNCHITTEST                1074
#define IDC_LIMITFPS                    1075
#define IDC_SKIPFPS                     1076
#define IDC_SHOWFPS                     1077
#define IDC_HIDEMULTIMONITOR            1078
#define IDC_TIMESTRETCH                 1079
#define IDC_HOOKOPENGL                  1080
#define IDC_WALLPAPERMODE               1081
#define IDC_HOOKGDI                     1082
#define IDC_SHOWFPSOVERLAY              1083
#define IDC_FAKEVERSION                 1084
#define IDC_COMBOTS                     1085
#define IDC_NOPALETTEUPDATE             1086
#define IDC_MARKBLIT                    1087
#define IDC_LISTTS                      1088
#define IDC_LISTFAKE                    1089
#define IDC_TABPANEL                    1090
#define IDC_WINDOWIZE                   1091
#define IDC_NOBANNER                    1092
#define IDC_STARTDEBUG                  1093
#define IDC_WIREFRAME                   1094
#define IDC_DISABLEGAMMARAMP            1095
#define IDC_FORCEWINRESIZE              1096
#define IDC_FORCE16BPP                  1097
#define IDC_FORCEHOOKOPENGL             1098
#define IDC_DESKTOPCENTER               1099
#define IDC_COORDINATES                 1100
#define IDC_SUPPRESSD3DEXT              1101
#define IDC_FULLRECTBLT                 1102
#define IDC_TIMESPEED                   1103
#define IDC_HOOKDLLS                    1104
#define IDC_HOOKENABLED                 1105
#define IDC_DESKTOPWORKAREA             1106
#define IDC_FIXD3DFRAME                 1107
#define IDC_TIMESLIDER                  1108
#define IDC_BLACKWHITE                  1109
#define IDC_SAVECAPS                    1110
#define IDC_SINGLEPROCAFFINITY          1111
#define IDC_HOOKDI                      1112
#define ID_MODIFY                       32771
#define ID_DELETE                       32772
#define ID_ADD                          32773
#define ID_EXPLORE                      32774
#define ID_RUN                          32777
#define ID_PRUN                         32778
#define ID_PMODIFY                      32779
#define ID_PDELETE                      32780
#define ID_PADD                         32781
#define ID_PEXPLORE                     32782
#define ID_VIEWLOG                      32787
#define ID_TASK_KILL                    32789
#define ID_FILE_SORTPROGRAMSLIST        32790
#define ID_FILE_CLEARALLLOGS            32792
#define ID_FILE_HOOK                    32794
#define ID_HOOK_START                   32795
#define ID_HOOK_STOP                    32796
#define ID_LOG_VIEW                     32799
#define ID_LOG_DELETE                   32800
#define ID_PLOG_VIEW                    32801
#define ID_PLOG_DELETE                  32802
#define ID_FILE_TASK                    32803
#define ID_TASK_PAUSE                   32805
#define ID_FILE_GOTOTRAYICON            32807
#define ID_TRAY_RESTORE                 32808
#define ID_VIEW_STATUS                  32809
#define ID_DXAPP_EXIT                   32810
#define ID_SAVEFILE                     32810
#define ID_VIEW_TIMESLIDER              32811
#define ID_DXWND_VI                     32812
#define ID_VIEW_STATUS32813             32813
#define ID_VIEW_TIMESLIDER32814         32814
#define ID_VIEW_STATUS3                 32815
#define ID_KILL_PAUSE                   32816
#define ID_KILL_RESUME                  32817
#define ID_KILL_KILL                    32818
#define ID_TASK_RESUME                  32819
#define ID_FILE_IMPORT                  32820
#define ID_INDEX0_EXPORT                32821
#define ID_PEXPORT                      32822
#define ID_PKILL                        32823

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32825
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
